"""
Contenu de l'onglet TUTO.

Structure de donnees pure : utilisable par le CLI (python cli.py tuto) et
par l'interface graphique. Aucune dependance.
"""

SECTIONS = [
    {
        "titre": "Pourquoi cette application",
        "lignes": [
            "Le librarian Korg a un parametre LEVEL qui plafonne a 100 %.",
            "Il ne peut que BAISSER le volume, jamais le monter.",
            "Un sample enregistre trop faible reste trop faible, et rien",
            "dans l'application officielle ne permet de retravailler le son.",
            "",
            "Volca Gain fait le traitement AVANT le transfert, puis envoie",
            "directement par SYNC IN. Le librarian devient inutile.",
        ],
    },
    {
        "titre": "Reperer un sample trop faible",
        "lignes": [
            "Onglet TRAITEMENT > Analyser. Regarde la colonne RMS :",
            "",
            "  au-dessus de -12 dB : deja fort, preset doux suffit",
            "  entre -12 et -20 dB : normal, preset punch",
            "  en dessous de -20 dB : trop faible, preset max",
            "",
            "La CRETE ne dit rien du volume percu. Un sample peut avoir",
            "une crete a 0 dB et sonner tres faible : c'est le RMS qui",
            "compte, c'est-a-dire l'energie moyenne.",
            "",
            "Le LUFS est encore plus fiable : il tient compte du fait que",
            "l'oreille est moins sensible aux graves.",
        ],
    },
    {
        "titre": "Quel preset choisir",
        "lignes": [
            "doux  - normalisation crete seule, garde toute la dynamique.",
            "        Pour les samples deja bien enregistres.",
            "",
            "punch - le bon defaut. Compression douce, attaque accentuee,",
            "        niveau -13 dB. Marche sur presque tout.",
            "",
            "max   - le plus fort possible. Kicks, claps, one-shots courts.",
            "        A eviter sur les nappes : ca respire.",
            "",
            "loop  - boucles rythmiques ou melodiques. Fondus minuscules",
            "        pour ne pas casser le raccord en lecture bouclee.",
            "",
            "sub   - basses et subs. Coupe tres bas (20 Hz) et pas de",
            "        saturation : le grave reste propre.",
            "",
            "voix  - voix et field recordings. Coupe a 90 Hz pour virer",
            "        le souffle, les bruits de manipulation, le vent.",
        ],
    },
    {
        "titre": "Ce que fait la chaine de traitement",
        "lignes": [
            "1. Offset DC : recentre le signal. Un sample decale perd de",
            "   la marge des deux cotes.",
            "",
            "2. Passe-haut : coupe le grave inaudible. C'est souvent",
            "   +3 dB gratuits, l'energie sous 40 Hz mange la dynamique",
            "   sans qu'on l'entende.",
            "",
            "3. Coupe des silences : gagne de la memoire volca.",
            "",
            "4. Transient shaper : accentue l'attaque independamment du",
            "   volume. Plus utile qu'un compresseur sur les percussions.",
            "",
            "5. Compression : reduit l'ecart crete/moyenne, donc permet",
            "   de monter beaucoup plus haut avant d'ecreter.",
            "",
            "6. Saturation : ajoute des harmoniques au lieu d'ecreter.",
            "   Le son parait plus fort sans monter le niveau.",
            "",
            "7. Mise a niveau RMS ou LUFS : la cible de volume.",
            "",
            "8. Fondus courts : evite les clics au declenchement.",
            "",
            "9. Limiteur avec lookahead : plafonne sans distordre.",
        ],
    },
    {
        "titre": "Le curseur de gain et la qualite",
        "lignes": [
            "ECOUTER ORIGINAL et ECOUTER TRAITE, dans l'onglet TRAIT.,",
            "font entendre le premier son du dossier avec les reglages",
            "courants. De quoi choisir un preset sans traiter tout le",
            "dossier pour rien.",
            "",
            "GAIN (curseur) : DEPLACE LA CIBLE du preset, il ne s'ajoute",
            "pas apres coup. C'est important : ajoute a la fin, le gain",
            "serait repris par le limiteur et ne changerait presque rien",
            "sur un preset qui pousse deja au plafond.",
            "Commence par +/- 2 dB, c'est deja audible.",
            "",
            "QUALITE (envoi) : 16 = qualite maximale, transfert le plus",
            "long. Descendre a 12 ou 10 divise la duree du transfert.",
            "Sur des percussions courtes la difference s'entend a peine.",
            "",
            "Astuce : la volca compresse les samples en interne. Un signal",
            "bien chaud au depart subit moins de bruit de quantification.",
            "C'est une raison de plus de ne pas envoyer un sample faible.",
        ],
    },
    {
        "titre": "L'editeur : decouper et comparer",
        "lignes": [
            "Onglet EDIT. > Charger un WAV. La forme d'onde s'affiche.",
            "",
            "DECOUPE : fais glisser les deux poignees orange. La zone",
            "gardee reste en couleur, le reste devient gris. Le compteur",
            "affiche debut, fin et duree exacte au milliseconde.",
            "",
            "CALER ZERO : deplace les deux bornes vers le passage par",
            "zero le plus proche. A faire systematiquement : c'est ce qui",
            "supprime les clics au declenchement.",
            "",
            "ROGNER : reduit vraiment le sample a la selection. Utile",
            "pour enchainer plusieurs decoupes successives.",
            "",
            "ANNULER revient en arriere, jusqu'a douze etapes. Couvre le",
            "rognage, l'inversion et le changement de canal.",
            "",
            "La page defile : fais glisser vers le haut pour atteindre les",
            "commandes du bas.",
            "",
            "A / B : A joue la selection telle quelle, B la joue avec le",
            "preset et le gain appliques. Le trait bleu suit la lecture.",
            "Le journal affiche RMS et LUFS des deux : tu vois et tu",
            "entends la difference.",
            "",
            "VERS UN SLOT : place le resultat deja traite dans un slot.",
            "L'application demande le NOM a donner au slot avant de le",
            "remplir. Le preset du slot passe a doux pour ne pas traiter",
            "le son une deuxieme fois.",
            "",
            "EXPORTER WAV demande aussi un nom de fichier. C'est le moment",
            "le plus pratique pour renommer : le son vient d'etre decoupe",
            "et traite, tu sais exactement ce que c'est.",
            "",
            "Pour renommer plus tard : onglet SLOTS, appuie sur un slot",
            "rempli, bouton RENOMMER.",
            "",
            "Astuce memoire : rogner serre avant d'envoyer est le moyen",
            "le plus simple de faire tenir un kit dans les 65 secondes.",
        ],
    },
    {
        "titre": "Reglages fins : les onze curseurs",
        "lignes": [
            "Onglet EDIT. > bouton FINS. Onze curseurs, un par etage de la",
            "chaine. Le preset selectionne sert de point de depart.",
            "",
            "Passe-haut        coupe le grave. 20-40 Hz pour un sub,",
            "                  90-120 Hz pour une voix.",
            "Saturation force  intensite de l'effet.",
            "Saturation dosage melange sec/sature. 0 = desactive.",
            "Compression seuil a partir d'ou ca compresse.",
            "Compression taux  1:1 = rien, 6:1 = ferme.",
            "Transitoire       attaque et tenue, en dB.",
            "Porte de bruit    -80 = desactivee.",
            "Niveau vise       la cible. C'est le reglage qui compte le plus.",
            "Plafond           limite de sortie, laisse -0,3 dB.",
            "Raccord de boucle fondu enchaine fin sur debut, pour les loops.",
            "",
            "ECOUTER teste sans rien changer. APPLIQUER garde les reglages",
            "pour cette session. ENREGISTRER en fait un vrai preset, qui",
            "apparait ensuite partout, y compris en ligne de commande, et",
            "survit au redemarrage.",
            "",
            "CANAL : sur un WAV stereo, tu peux prendre le canal gauche,",
            "le droit, la moyenne, ou SIDE. Side isole ce qui n'est pas au",
            "centre : parfois de quoi recuperer une nappe ou une reverb",
            "sans la voix qui est devant.",
            "",
            "INVERSER retourne la polarite. Inaudible seul, mais change",
            "tout quand deux samples se superposent sur la volca.",
        ],
    },
    {
        "titre": "Un kit coherent",
        "lignes": [
            "Probleme classique : tu montes un kit, et a l'usage certains",
            "pads sonnent bien plus fort que d'autres. Normal : le preset",
            "max ne vise pas le meme niveau que doux ou loop.",
            "",
            "EGALISER LE KIT (onglet SLOTS) regle ca. Il mesure le niveau",
            "percu reel de chaque slot, puis ajuste leurs gains pour que",
            "tous repondent au meme volume.",
            "",
            "Deux details qui comptent :",
            "",
            "Il aligne sur LE PLUS FAIBLE, jamais l'inverse. Un sample",
            "deja au plafond ne peut pas devenir plus fort : le limiteur",
            "reprendrait le gain ajoute. En attenuant, la correction est",
            "toujours realisable.",
            "",
            "Il ITERE. Le limiteur rend la reponse au gain non lineaire,",
            "donc il mesure le resultat, corrige, et recommence jusqu'a",
            "tomber sous 0,3 dB d'ecart.",
            "",
            "Compte environ une seconde pour cinq slots.",
            "",
            "ENVOI PARTIEL : le bouton SELECTION change le comportement",
            "des slots. En mode selection, un appui coche ou decoche un",
            "slot au lieu de l'ouvrir ; les slots choisis passent en cyan",
            "et ENVOYER affiche leur nombre. Tres pratique pour corriger",
            "un seul son sans retransferer les cent autres.",
            "Ressors du mode selection pour tout envoyer.",
            "",
            "RENOMMER : appuie sur un slot rempli, puis Renommer. Le nom",
            "est une etiquette locale : la volca ne stocke aucun nom, c'est",
            "le fichier projet qui s'en souvient. Il suit le slot quand tu",
            "le deplaces, et voyage avec le kit exporte.",
            "",
            "RANGEMENT : appuie sur un slot rempli, puis Deplacer,",
            "Echanger ou Copier, et choisis la destination. Deplacer vers",
            "un slot occupe fait un echange automatiquement. TASSER",
            "regroupe tout au debut, sans trou.",
        ],
    },
    {
        "titre": "Memoire : 65 s, ou 130 s en sample2",
        "lignes": [
            "volca sample  : 100 emplacements, environ 65 s de memoire.",
            "volca sample2 : 200 emplacements, environ 130 s.",
            "",
            "IMPORTANT : le selecteur MACHINE, en haut de l'onglet SLOTS,",
            "decide du nombre d'emplacements. Tant qu'il affiche",
            "'volca sample', tu n'as que 100 slots meme si ta machine en a",
            "200. Passe-le sur 'volca sample2' et la grille double.",
            "",
            "Les onglets SLOTS et PATT. defilent : fais glisser vers le",
            "haut pour atteindre les boutons du bas.",
            "La grille et la jauge s'adaptent. Passer de sample2 a sample",
            "supprime les slots au-dela de 99 : l'application previent avant.",
            "",
            "Ce n'est pas beaucoup. Trois leviers pour tenir :",
            "",
            "1. Couper les silences (les presets punch et max le font)",
            "",
            "2. Raccourcir les samples. Un kick n'a pas besoin de 2 s,",
            "   300 ms suffisent souvent.",
            "",
            "3. Baisser le taux d'echantillonnage. Le Syro accepte",
            "   n'importe quel Fs. Une nappe sombre a 22 kHz sonne pareil",
            "   et coute moitie moins cher. L'application propose un taux",
            "   automatiquement quand le sample n'a pas d'aigu.",
            "",
            "Le bouton OPTIMISER (onglet SLOTS) fait le 3 tout seul : il",
            "analyse chaque sample, detecte ceux qui n'ont pas d'aigu et",
            "leur affecte un taux reduit. Les slots optimises portent une",
            "etoile. Le taux est enregistre dans le fichier projet et",
            "applique au moment de l'envoi : le son d'origine n'est jamais",
            "modifie sur le disque.",
            "",
            "La jauge passe en rouge au depassement.",
        ],
    },
    {
        "titre": "Reussir le transfert",
        "lignes": [
            "1. Cable jack 3,5 mm : sortie casque vers SYNC IN de la volca",
            "2. Volume de l'appareil A FOND",
            "3. Bluetooth COUPE (sinon le son part ailleurs)",
            "4. Aucun egaliseur, pas de Dolby, pas d'Adapt Sound",
            "5. Lancer, puis ne toucher a rien jusqu'a la fin",
            "",
            "Un compte a rebours s'affiche pendant le transfert, avec la",
            "barre de progression et les secondes restantes. Tant qu'il",
            "tourne, la volca ecoute : ne coupe pas le son, ne verrouille",
            "pas l'ecran, ne change pas d'application.",
            "",
            "La volca affiche sa progression et redemarre a la fin.",
            "",
            "Si ca echoue : c'est presque toujours le volume trop bas ou",
            "un traitement audio du telephone qui abime le signal.",
            "",
            "L'envoi ECRASE le slot sans demander confirmation. Teste sur",
            "un slot vide ou dont tu n'as pas besoin.",
        ],
    },
    {
        "titre": "Fichiers projet",
        "lignes": [
            "Sauver projet cree un fichier .volca.json qui memorise quel",
            "WAV va dans quel slot, avec son preset et son gain.",
            "",
            "Interet : retrouver exactement son kit, le re-envoyer apres",
            "avoir bidouille la volca, en avoir plusieurs (kit techno,",
            "kit live, kit demo), les partager, les versionner dans git.",
            "",
            "Le fichier ne contient pas les sons, seulement les chemins.",
            "Ne deplace pas tes WAV apres avoir sauve.",
            "",
            "Le dernier projet ouvert est rouvert automatiquement au",
            "lancement suivant : tu retrouves ton kit sans rien faire.",
        ],
    },
    {
        "titre": "Patterns : 10 sequences de 16 pas",
        "lignes": [
            "La volca stocke 10 patterns. Chacun contient 10 parties, et",
            "chaque partie declenche UN sample sur 16 pas.",
            "",
            "Onglet PATTERN. Choisis une partie, son sample, puis appuie",
            "sur les pas pour les activer. Les quatre temps sont marques",
            "pour se reperer.",
            "",
            "Par partie tu regles aussi : le niveau, et les fonctions",
            "LOOP (le sample boucle), REVERB, REVERSE (lecture a l'envers)",
            "et MUTE.",
            "",
            "ECOUTER joue le pattern avec les sons places dans tes SLOTS,",
            "au tempo choisi. Les parties muettes sont ignorees, comme sur",
            "la machine. Si un slot est vide, la partie est passee et",
            "l'application te dit lesquels manquent.",
            "",
            "C'est une simulation faite sur le telephone : elle sert a",
            "verifier le rythme avant d'envoyer, pas a remplacer la volca.",
            "",
            "ENVOYER ecrit le pattern dans l'emplacement choisi, 0 a 9.",
            "Meme branchement que pour les samples : casque vers SYNC IN.",
            "",
            "ATTENTION : l'envoi ECRASE le pattern de destination sans",
            "demander. Teste sur un emplacement dont tu n'as pas besoin.",
            "",
            "Le transfert ne va que dans un sens : la volca ne sait rien",
            "renvoyer. Impossible de recuperer un pattern joue sur la",
            "machine, il faut le refaire dans l'application.",
            "",
            "MOTIONS : les patterns peuvent contenir des enregistrements",
            "de mouvements de potards. L'application les PRESERVE quand",
            "elle ouvre et reenregistre un fichier, mais ne permet pas",
            "encore de les modifier ni de les effacer.",
            "",
            "Les fichiers .dat font 2624 octets, format Korg. Ceux du SDK",
            "(pattern/preset_pattern_01.dat et suivants) s'ouvrent tels",
            "quels et servent de point de depart.",
            "",
            "En ligne de commande :",
            "  python cli.py pattern creer mon.dat --partie 1 --sample 3 \\",
            "        --pas 1,5,9,13",
            "  python cli.py pattern infos mon.dat",
            "  python cli.py pattern envoyer mon.dat --slot 0 --jouer",
        ],
    },
    {
        "titre": "Importer une sauvegarde du librarian Korg",
        "lignes": [
            "Un fichier .vlcspllib est une sauvegarde faite par le",
            "librarian officiel : tous les sons de la machine, avec leurs",
            "noms et leur placement.",
            "",
            "Onglet SLOTS > Kit > IMPORTER UNE SAUVEGARDE KORG.",
            "",
            "L'application en extrait chaque son en WAV, reconstruit le",
            "projet avec les bons numeros de slot et les noms d'origine,",
            "et regle la machine automatiquement (sample ou sample2).",
            "",
            "Les sons sortent BRUTS, tels qu'ils etaient dans la machine.",
            "Aucun traitement n'est applique : c'est une restauration.",
            "Passe ensuite par TRAIT. ou EDIT. pour les retravailler.",
            "",
            "Compte quelques secondes pour 180 sons.",
            "",
            "PATTERNS : un fichier .vlcsplpatt ne contient que des",
            "patterns, sans aucun son. Ouvre-le depuis l'onglet PATT. >",
            "OUVRIR : l'application liste les patterns qu'il contient et",
            "charge celui que tu choisis dans l'editeur.",
            "",
            "La conversion garde le sample, les pas, le niveau et les",
            "fonctions. Elle abandonne les MOTIONS : leur disposition",
            "differe entre les deux machines.",
            "",
            "Attention : l'editeur travaille au format de la volca sample",
            "PREMIERE generation (2624 octets). Le SDK Korg embarque ne",
            "sait envoyer que celui-la. Un pattern de sample2 peut donc",
            "etre lu et retravaille, mais l'envoi vise le format ancien.",
            "",
            "  python cli.py librairie infos sauvegarde.vlcspllib",
            "  python cli.py librairie patterns sauvegarde.vlcspllib",
            "  python cli.py librairie importer sauvegarde.vlcspllib -o ~/kits",
            "",
            "Le format n'est pas documente par Korg : il a ete reconstitue",
            "en analysant un vrai fichier. Si un import echoue sur une",
            "sauvegarde particuliere, signale-le.",
        ],
    },
    {
        "titre": "Kit portable : partager, deplacer",
        "lignes": [
            "Un fichier projet ne contient que des CHEMINS. Il ne survit",
            "donc pas a un changement de telephone, et ne sert a rien si",
            "tu l'envoies a quelqu'un : les sons ne suivent pas.",
            "",
            "Un KIT, si. Onglet SLOTS > Kit > Exporter. Tu obtiens un zip",
            "qui contient les WAV DEJA TRAITES, leur placement dans les",
            "100 slots, et les reglages de chaque slot.",
            "",
            "A l'import, les sons sont extraits et le projet reconstruit.",
            "Les slots passent en preset doux : le son a deja ete traite a",
            "l'export, inutile de recommencer.",
            "",
            "Le taux reduit des slots optimises est conserve dans le",
            "projet, pas grave dans le fichier : sinon la relecture en",
            "44,1 kHz annulerait le gain de memoire.",
            "",
            "Le zip contient aussi un LISEZMOI qui liste tout, lisible",
            "sans l'application. Les WAV de samples/ sont des fichiers",
            "normaux, utilisables ailleurs.",
            "",
            "En ligne de commande :",
            "  python cli.py kit exporter mon_kit.volca.json",
            "  python cli.py kit infos recu.kit.zip",
            "  python cli.py kit importer recu.kit.zip -o ~/kits",
        ],
    },
    {
        "titre": "Trouver ses fichiers dans l'application",
        "lignes": [
            "Le selecteur de fichiers a une barre de RACCOURCIS en haut :",
            "Telechargements, Musique, Stockage interne, Carte SD. Un appui",
            "t'y amene directement, sans naviguer depuis la racine.",
            "",
            "En bas, un champ affiche le chemin courant. Tu peux y TAPER un",
            "chemin et valider : c'est le moyen le plus sur quand un dossier",
            "n'apparait pas dans la liste.",
            "",
            "  /storage/emulated/0/Download",
            "  /storage/emulated/0/Music/mes_samples",
            "",
            "POUR CHOISIR UN FICHIER, il faut appuyer sur le FICHIER dans la",
            "liste avant CHOISIR. Appuyer sur Choisir sans rien selectionner",
            "ne valide pas le dossier courant : l'application te le dit.",
            "",
            "SI TON DOSSIER N'APPARAIT PAS :",
            "",
            "1. Verifie qu'il est bien dans le stockage interne et pas dans",
            "   un espace prive d'une autre application.",
            "",
            "2. Android recent restreint l'acces hors des dossiers",
            "   standards. Le plus simple est de mettre tes WAV dans",
            "   Telechargements ou Musique.",
            "",
            "3. Si l'application n'a jamais demande l'acces au stockage,",
            "   va dans les parametres Android : Applications > MOC'TA BASS",
            "   > Autorisations > Fichiers et contenus multimedia.",
            "",
            "3bis. Sur Android 11 et plus, cette autorisation ne suffit",
            "   pas pour parcourir librement les dossiers. Utilise le",
            "   bouton AUTORISER L'ACCES AUX FICHIERS, en vert dans le",
            "   selecteur : il ouvre l'ecran systeme dedie. Autorise, puis",
            "   reviens dans l'application.",
            "",
            "4. En dernier recours, tape le chemin complet dans le champ.",
        ],
    },
    {
        "titre": "Ou sont mes fichiers",
        "lignes": [
            "Tout ce que l'application ecrit va dans son dossier de",
            "travail. Sur Android c'est un dossier prive, affiche dans le",
            "journal a chaque enregistrement : lis la ligne, elle donne le",
            "chemin complet.",
            "",
            "Y sont ecrits :",
            "  mon_kit.volca.json   ton projet",
            "  presets.volca.json   tes presets personnalises",
            "  etat.volca.json      le dernier projet ouvert",
            "  transfert.wav        le dernier flux genere",
            "  *.kit.zip            les kits exportes",
            "  *.dat                les patterns enregistres",
            "",
            "Les samples TRAITES vont dans volca_out/, DANS LE DOSSIER DE",
            "L'APPLICATION. Android refuse qu'une application ecrive des",
            "fichiers audio dans un espace partage comme Telechargements,",
            "meme quand la lecture y est autorisee.",
            "",
            "Le journal affiche le chemin de sortie a chaque traitement :",
            "lis la ligne Sortie, elle donne l'emplacement exact.",
            "",
            "Tes fichiers d'origine ne sont jamais modifies.",
            "",
            "Pour recuperer les sons traites hors de l'application, passe",
            "par Exporter le kit : le zip est ecrit dans un endroit",
            "accessible depuis un gestionnaire de fichiers.",
            "",
            "Pour recuperer un fichier depuis un ordinateur ou une autre",
            "application, passe par Exporter le kit : le zip, lui, est",
            "ecrit dans un endroit accessible.",
        ],
    },
    {
        "titre": "Quand ca plante",
        "lignes": [
            "L'application ne disparait pas en silence. Si un onglet",
            "echoue, il est remplace par un ECRAN VERT affichant la trace",
            "complete de l'erreur, et les autres onglets continuent de",
            "fonctionner normalement.",
            "",
            "Sur cet ecran :",
            "  le titre en rouge indique QUEL onglet a echoue",
            "  le texte vert est la trace, elle defile",
            "  le bouton COPIER la met dans le presse-papier",
            "",
            "La meme trace est aussi ecrite dans un fichier :",
            "  /sdcard/Download/moctabass_crash.txt",
            "",
            "Pour signaler un probleme, envoie cette trace. C'est elle qui",
            "contient la ligne exacte ; sans elle, on corrige a l'aveugle.",
            "",
            "Le fichier est ecrase a chaque plantage : recupere-le avant",
            "de relancer l'application si tu veux le garder.",
        ],
    },
    {
        "titre": "En ligne de commande",
        "lignes": [
            "Tout est aussi disponible dans un terminal :",
            "",
            "  python cli.py info samples/",
            "  python cli.py traiter samples/ -o out/ -p punch",
            "  python cli.py projet creer mon_kit --dossier out/",
            "  python cli.py memoire mon_kit.volca.json",
            "  python cli.py projet optimiser mon_kit.volca.json",
            "  python cli.py projet egaliser mon_kit.volca.json",
            "  python cli.py projet deplacer mon_kit.volca.json 5 --vers 12",
            "  python cli.py projet tasser mon_kit.volca.json",
            "  python cli.py projet renommer mon_kit.volca.json 3 --titre Kick",
            "  python cli.py projet modele mon_kit.volca.json --modele sample2",
            "  python cli.py envoyer mon_kit.volca.json --jouer",
            "  python cli.py rapide 3 kick.wav --jouer",
            "  python cli.py effacer 3,7-9 --jouer",
            "  python cli.py syro",
            "  python cli.py presets -d punch",
            "  python cli.py tuto -s 12",
            "",
            "Aucune dependance : ca marche dans Termux tel quel.",
        ],
    },
]


def titres():
    return [s["titre"] for s in SECTIONS]


def texte(index=None):
    """Rend le tutoriel en texte. index=None -> tout."""
    cibles = SECTIONS if index is None else [SECTIONS[index]]
    out = []
    for s in cibles:
        out.append("=== %s ===" % s["titre"].upper())
        out.extend(s["lignes"])
        out.append("")
    return "\n".join(out)
